_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.RandomCrop
    size: 32
    padding: 4
  - _target_: torchvision.transforms.RandomHorizontalFlip
  - _target_: torchvision.transforms.ToTensor
