# Environment configuration
your_name:
  BASE_MODEL_PATH: '/set/path/here'
  CIFAR_ROOT: '/set/path/here'
  IMAGENET_ROOT: '/set/path/here'
  SVHN_ROOT: '/set/path/here'
  PLACES_ROOT: '/set/path/here'
  RPC_ROOT: '/set/path/here'
  ICARTOONFACE_ROOT: '/set/path/here'
  SHAPES3D_ROOT: '/set/path/here'
  FOUR_SHAPES_ROOT: '/set/path/here'
  AFHQV2_ROOT: '/set/path/here'
  MOEIMOUTO_FACES_ROOT: '/set/path/here'
  IMAGENETO_ROOT: '/set/path/here'
  CUDA_VISIBLE_DEVICES: ''
