project_root: /system/user/publicwork/hofmann/hopfield_boosting

cifar-10: /publicdata
cifar-100: /publicdata
imagenet: /system/user/publicwork/hofmann/Poem/datasets/unlabeled_datasets/ImageNet
svhn: /system/user/publicwork/hofmann/hopfield_classifiers/datasets/ood_datasets/svhn/
lsun-crop: /system/user/publicwork/hofmann/hopfield_classifiers/datasets/ood_datasets/LSUN
lsun-resize: /system/user/publicwork/hofmann/hopfield_classifiers/datasets/ood_datasets/LSUN_resize
isun: /system/user/publicwork/hofmann/hopfield_classifiers/datasets/ood_datasets/iSUN
places: /system/user/publicwork/hofmann/hopfield_classifiers/datasets/ood_datasets/places365/
textures: /system/user/publicwork/hofmann/hopfield_classifiers/datasets/ood_datasets/dtd/images
mnist: /publicdata
fashion_mnist: /publicdata
