project_root: /placeholder

cifar-10: /placeholder
cifar-100: /placeholder
imagenet: /placeholder
svhn: /placeholder
lsun-crop: /placeholder
lsun-resize: /placeholder
isun: /placeholder
places: /placeholder
textures: /placeholder
mnist: /placeholder
fashion_mnist: /placeholder
